### ISSUE TITLE
Licensing issues and issues with journal copyright agreements (for figures and text)

### ISSUE THREAD

**Issue by dmzuckerman** [livecomsjournal/livecomsjournal.github.io#42] opened 2017-09-13 00:07 UTC
Our very open and/or inconsistent licensing (if left to authors) may make other journals unwilling to grant permission for reprinting figures.  This could prove a hassle for some authors, particularly with review articles.

Also, even though figure permissions for LiveCoMS figures may be implicit in the license adopted, we probably should have an explicit section for that to avoid redundant emails on the subject.

**Comment by davidlmobley** [comment] 2017-09-13 05:07
> Our very open and/or inconsistent licensing (if left to authors) may make other journals unwilling to grant permission for reprinting figures. This could prove a hassle for some authors, particularly with review articles.

@dmzuckerman - just to make sure I'm clear: Are you thinking about the case where we reprint figures from a journal here, or where a journal reprints figures which appeared here? 

I think in the former case, the journal would likely give us rights to reprint them under a particular more restrictive license, which would require us to grant special permissions. In the case of other journals reprinting figures which have first appeared here -- the journal would have to accept that they are not being given exclusive copyright to the figures, in a somewhat similar manner to what they would for a federal government paper, etc. Perhaps this could be a hassle in some cases; is that what you're worried about? 

> Also, even though figure permissions for LiveCoMS figures may be implicit in the license adopted, we probably should have an explicit section for that to avoid redundant emails on the subject.

I think I need to be more clear which side of the issue you're trying to address.

**Comment by dmzuckerman** [comment] 2017-09-14 00:48
I was worried about both.  I just foresee hassles.  Not sure what we can do to prevent it.
________________________________

**Comment by davidlmobley** [comment] 2017-09-14 17:53
@dmzuckerman - oddly enough, I just realized that the issue of licenses and preprints is a lot more, er, *interesting* than I thought and extends far beyond LiveCoMS. Specifically, I just submitted a paper to ChemRxiv, the ACS preprint server, under the CC-BY license that's one of just several options allowed there. As I was submitting, I thought about the fact that we plan to submit to an ACS journal, which will require us to transfer copyright of everything (including our figures -- http://pubs.acs.org/paragonplus/copyright/jpa_form_a.pdf ) to ACS, and wondered whether I should worry about these issues. Eventually I decided to plunge ahead, but it currently seems like there's a bit of a contradiction:
- The ACS preprint server only allows creative commons licenses which explicitly grant rights for reuse by others
- Most ACS journals require agreement to the above copyright policy which superficially seems contradictory to the CC licenses

I'm asking ACS if the two are incompatible. (It's worth noting that CC licenses are also used frequently on BioRxiv, etc. -- they're common in the preprint community.)

My perspective here is that this is going to be a hassle a for people a lot more broadly than LiveCoMS and we probably can just stick with what other preprint people are doing (use CC licenses) for now and wait for the bigger fish (ACS, etc.) to sort out how to handle copyright agreements/licensing in the new world we're arriving in.

**Comment by davidlmobley** [comment] 2017-09-14 17:53
In other words, I don't see how we can prevent it but the problem is a lot bigger than LiveCoMS and not ours to fix (it's a problem with journals' copyright agreements).

**Comment by dmzuckerman** [comment] 2017-09-14 18:03
Great points - thanks for the careful consideration.  So long as it's on our radar and we're following community standars, we should be fine.
________________________________

**Comment by davidlmobley** [comment] 2017-09-14 18:04
Marking as closed for now, but we can reawaken it if needed.

**Closed by davidlmobley** 2017-09-14 18:04 UTC

**Comment by davidlmobley** [comment] 2017-09-14 23:44
For the record, this discussion is also particularly helpful: http://blog.dhimmel.com/biorxiv-licenses/#comment-3070230004

**Comment by davidlmobley** [comment] 2017-09-15 15:59
Had a good conversation with Darla Henderson, the ACS open access/preprint person (driving force behind ChemRxiv) on this, and she says basically:
- ACS is not going to stop you from signing the journal publishing agreement if your article is CC-BY so it doesn't pose problems on that end of things
- There is a lot here that still has to be sorted out and they and other publishers are working on it
- The main thing to worry about is if you try and publish in a journal which doesn't allow preprints. But if it allows preprints, then it's going to be having to deal with this heterogeneity/complexity of licenses which is not yet sorted out
- It is possible that eventually journals might start requiring you to publish under CC-BY if your preprint is CC-BY (e.g. currently ACS has the option for you to pay a good chunk of change to do this) but that hasn't happened yet

They are apparently talking with BioRxiv and others about the issue as well.

So I think the upshot is: It's a potentially important issue, and one which isn't resolved yet, but also it's on various people's radar as something they have to work on. So we're on relatively safe or at least well-trodden ground in terms of using CC-BY for preprints.
